telegram:
  bot_token:
  channel_name: "@channel"
  auth_key: test

twitter:
  bearer_token:
  auth_token:

dropbox:
  access_token:
  save_path: "/test"

pixiv:
  username:
  password:
  client_id:
  client_secret:
  initial_access_token:
  initial_refresh_token:

db:
  db_path: ./external/bot.db
  url_bucket: url
  like_bucket: like
  auth_bucket: auth

danbooru:
  username:
  key: 

bluesky:
  # No authentication required for public posts

instagram:
  # No authentication required for public posts

s3:
  bucket:
  region: ap-northeast-1
  save_path: "."
  access_key_id:
  secret_access_key:
